services:
#  db:
#    image: postgres:16
#    restart: always
#    environment:
#     - POSTGRES_USER=myuser
#     - POSTGRES_PASSWORD=mypassword
#     - POSTGRES_DB=mydb
#    ports:
#      - "5433:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

  test_db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - "5434:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data


volumes:
  db_data:
  test_db_data: